apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-trace-emitter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-trace-emitter
  template:
    metadata:
      labels:
        app: opentelemetry-trace-emitter
    spec:
      containers:
        - name: opentelemetry-trace-emitter
          image: vergissberlin/opentelemetry-trace-emitter:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
            requests:
              memory: '64Mi'
              cpu: '250m'
          env:
            - name: OTEL_COLLECTOR_ENDPOINT
              value: 'http://otel-collector:4317'
