name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image latest
        run: cd app && docker build . --file Dockerfile --tag opentelemtry-trace-emitter:latest
      - name: Push the Docker image latest
        run: docker push opentelemtry-trace-emitter:latest
